apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nk-csi-kv
  namespace: default
spec:
  provider: azure
  secretObjects:                       # [OPTIONAL] if not provided, will default to all objects in the secret provider class
    - secretName: poc-cert             # [OPTIONAL] if not provided, will default to objectName
      type: kubernetes.io/tls          # [OPTIONAL] if not provided, will default to 'Opaque' (can be 'kubernetes.io/tls', 'kubernetes.io/dockerconfigjson' or 'Opaque')
      data:
        - objectName: poc-cert          # object name from .spec.parameters.objects array
          key: tls.crt                  # key from the secret object data
        - objectName: poc-cert
          key: tls.key
    - secretName: nadeem
      type: Opaque
      data:
        - objectName: nadeem
          key: nadeem
        
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 8a102019-fe07-4bee-bb58-4743a724234f   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: nk-csi-kv        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: poc-cert
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: nadeem
          objectType: secret
          objectVersion: ""
    tenantId: 7cb752a7-6dfd-429e-adc9-129f0ea3fcec                 # The tenant ID of the key vault