name: AKS Bicep Deployment

# Controls when the workflow will run
on: workflow_dispatch

permissions:
  id-token: write
  contents: read


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  deploy-resources:
    
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
         
      # Log into Azure
      - name: azure login  
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az deployment group create -g bicep-rg -f main.bicep --mode complete
