# This is a basic workflow to help you get started with Actions

name: Azure ARM Bicep

# Controls when the workflow will run
on: workflow_dispatch
  # Triggers the workflow on push or pull request events but only for the "main" branch
  

permissions:
  id-token: write
  contents: read

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch: <<<<<<<<<

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v1
        
      
      # Log into Azure
      - name: login  
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: interactive login
        uses: azure/CLI@v1
        
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az deployment group create -g vnet-hub-rg -f main.bicep --mode complete
